### ISSUE TITLE
Submit button disabled when previewMode = Yes

### ISSUE THREAD

**Issue by umyumm** [neilmorton/GetRated#1]
I added GetRated to my project.  In testing, I enabled previewMode = Yes.  

The rate popup appears as expected but the submit button is disabled and can't be clicked.  Is there any way to enable the submit button in previewMode to validate it goes to the correct place?

**Comment by neilmorton** [comment]
Hi @umyumm 

Thanks for reaching out. 

This is expected behaviour. 

I have just updated the Readme to add the following to a Notes section:

When calling `promptForRating` or `promptIfAllCriteriaMet` or if you enable `previewMode`, while your app is still in development mode, a rating/review request view is always displayed so that you can test the user interface and experience. However, as it is not possible to submit a rating from a development build, the Submit button will be greyed out. 

When your app is distributed via TestFlight, the rating/review request view will not be displayed.

Thanks. Neil.
